---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose-v2
    state: present

- name: Install Python
  apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started